plataforma/config/routes.rb
Rails.application.routes.draw do

  # get 'categoria/index'
  # get 'categoria/new'
  devise_for :users
  # get 'suppliers/index'
  # get 'suppliers/new'
  # get 'suppliers/show'
  # get 'suppliers/edit'
  # get 'products/index'
  # get 'products/new'
  # get 'products/show'
  # get 'products/edit'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :products
  resources :suppliers
  resources :pqrs
  resources :sale
  resources :categoria
end

plataforma/app/models/add_kind.rb
class AddKind < ApplicationRecord
end

plataforma/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

plataforma/app/models/categoria.rb
class Categoria < ApplicationRecord
end

plataforma/app/models/category.rb
class Category < ApplicationRecord
  has_many :suppliers
end

plataforma/app/models/detail_order.rb
class DetailOrder < ApplicationRecord
end

plataforma/app/models/invoice.rb
class Invoice < ApplicationRecord
end

plataforma/app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

plataforma/app/models/kind.rb
class Kind < ApplicationRecord
  has_many :pqrs
end

plataforma/app/models/order.rb
class Order < ApplicationRecord
end

plataforma/app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :kind
end

plataforma/app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :photos, PhotosUploader
  serialize :photos, JSON
  belongs_to :supplier
end

plataforma/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

plataforma/app/models/sale.rb
class Sale < ApplicationRecord
end

plataforma/app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
end

plataforma/app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :category
  has_many :products
end

plataforma/app/models/user.rb
 class User < ApplicationRecord

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

plataforma/app/controllers/products_controller.rb
# Esta clase Product funcionara como controlador para renderizar hacia la vista products con sus rescpectivos metodos
# @Autor: David Cabrera - Desarrollador
# @version: 1.0
# @see <a href="http://www.variedadesmary.com">Variedades Mary</a>

class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  # @param: Metodo index que traera todos los registros de la tabla productos de nuestra base de datos
  def index
    if current_user.has_role? :admin
      @products = Product.all
    else
    flash[:alert] = "No tiene acceso"
    redirect_to root_path
  end
  end

  # @param: Metodo new que permitira crear nuevo registro en la tabla productos
  def new
    @product = Product.new
  end

    # @param: Metodo create donde se creara el registro en la tabla productos
  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to products_path
      else
        render :new
      end
  end

  # @param: Metodo show que traera un registro en especifico de la tabla productos
  def show
    @products = Product.all
    @product = Product.find(params[:id])

  end
  # @param: Metodo edit que permitira editar un registro en la tabla productos
  def edit
    @product = Product.find(params[:id])
  end

  # @param: Metodo update que permitira actualizar nuevo registro en la tabla productos
  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to products_path
      else
        render :edit
      end
  end

  # @param: Metodo destroy que permitira eliminar un registro en la tabla productos
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :characteristic, :supplier_id, :mark, :kind, :discount, :reference, {photos: []})
  end

end

plataforma/app/helpers/categoria_helper.rb
module CategoriaHelper
end

plataforma/app/helpers/home_helper.rb
module HomeHelper
end

plataforma/app/helpers/pqrs_helper.rb
module PqrsHelper
end

plataforma/app/helpers/products_helper.rb
module ProductsHelper
end

plataforma/app/helpers/sale_helper.rb
module SaleHelper
end

plataforma/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

plataforma/app/views/products/edit.html.erb
<div class="form_products">
  <h1>Actualizar producto</h1>
  <%= simple_form_for @product, html: {multipart: true}  do |f| %>
    <%= f.input :name, label: 'Nombre' %>
    <%= f.input :price, label: 'Precio' %>
    <%= f.input :description, label: 'Descripcion', as: :text %>
    <%= f.input :characteristic, label: 'Caracteristica' %>
    <%= f.association :supplier, label_method: :fullname%>
    <%= f.input :mark, label: 'Marca' %>
    <%= f.input :kind, label: 'Tipo' %>
    <%= f.input :discount, label: 'Descuento' %>
    <%= f.input :reference, label: 'Referencia' %>
    <%= f.file_field :photos, multiple: true%>
    <%= f.file_field :photos, multiple: true %>
    <%= f.file_field :photos, multiple: true %>
    <br><br>
    <div class="d-grid gap-2">
      <%= f.button :submit, "Actualizar producto", :class => "btn btn-primary"%>
    </div>

  <% end %>
</div>

plataforma/app/views/products/index.html.erb
<h1>Productos</h1>
<hr>
 <table class="table table-striped table-hover">
   <tr>
     <thead class="">
       <th scope="col">Nombre</th>
       <th scope="col">Precio</th>
       <th scope="col">Descripcion</th>
       <th scope="col">Caracteristica</th>
       <th scope="col">Proveedor</th>
       <th scope="col">Marca</th>
       <th scope="col">Tipo</th>
       <th scope="col">Descuento</th>
       <th scope="col">Referencia</th>
       <th scope="col">Fotos</th>
       <th scope="col">Accion</th>
     </thead>
   </tr>
   <% @products.each do |product| %>
   <tr>
     <td><%= product.name %></td>
     <td><%= product.price %></td>
     <td><%= product.description %></td>
     <td><%= product.characteristic %></td>
     <td><%= product.supplier_id %></td>
     <td><%= product.mark %></td>
     <td><%= product.kind %></td>
     <td><%= product.discount %></td>
     <td><%= product.reference %></td>
     <td><%= link_to "Ver foto", product, :class => "btn btn-info" %></td>

     <td>
       <%= link_to "Editar", edit_product_path(product), :class => "btn btn-primary"%>
       <%= link_to "Eliminar", product, method: :delete, data: {confirm: "Desea eliminar este producto?"}, :class => "btn btn-danger" %>

     </td>
   </tr>
   <% end %>
 </table>

plataforma/app/views/products/new.html.erb
<div class="form_products">
  <h1>Crear nuevo producto</h1>
  <%= simple_form_for @product, html: {multipart: true}  do |f| %>
    <%= f.input :name, label: 'Nombre' %>
    <%= f.input :price, label: 'Precio' %>
    <%= f.input :description, label: 'Descripcion', as: :text %>
    <%= f.input :characteristic, label: 'Caracteristica' %>
    <%= f.association :supplier, label_method: :fullname%>
    <%= f.input :mark, label: 'Marca' %>
    <%= f.input :kind, label: 'Tipo' %>
    <%= f.input :discount, label: 'Descuento' %>
    <%= f.input :reference, label: 'Referencia' %>
    <%= f.file_field :photos, multiple: true%>
    <br><br>
    <div class="d-grid gap-2">
      <%= f.button :submit, "Crear producto", :class => "btn btn-primary"%>
    </div>

  <% end %>
</div>

plataforma/app/views/products/show.html.erb
<div class="section_show">
    <div class="div_fotos">
      <div class="div-foto_pequeña">
        <%= image_tag(@product.photos_urls[0], :class => 'imagen_producto_show') if @product.photos? %>
      </div>
      <div class="div-foto_pequeña">
        <%= image_tag(@product.photos_urls[1], :class => 'imagen_producto_show') if @product.photos? %>
      </div>
      <div class="div-foto_pequeña">
        <%= image_tag(@product.photos_urls[2], :class => 'imagen_producto_show') if @product.photos? %>
      </div>

    </div>
    <div class="div_foto">
      <%= image_tag(@product.photos_urls[0], :class => 'imagen_producto_show') if @product.photos? %>
    </div>
  </div>
  <div class="div_show">
    <h3><%= @product.name %></h3>
    <h3>$ <%= @product.price %></h3>
    <h3>Marca: <%= @product.mark %></h3>

    <%= button_to "Comprar" %>
    <%= button_to "Agregar al carrito" %>

  </div>