plataforma/config/routes.rb
Rails.application.routes.draw do

  # get 'categoria/index'
  # get 'categoria/new'
  devise_for :users
  # get 'suppliers/index'
  # get 'suppliers/new'
  # get 'suppliers/show'
  # get 'suppliers/edit'
  # get 'products/index'
  # get 'products/new'
  # get 'products/show'
  # get 'products/edit'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :products
  resources :suppliers
  resources :pqrs
  resources :sale
  resources :categoria
end

plataforma/app/models/add_kind.rb
class AddKind < ApplicationRecord
end

plataforma/app/models/categoria.rb
class Categoria < ApplicationRecord
end

plataforma/app/models/category.rb
class Category < ApplicationRecord
  has_many :suppliers
end

plataforma/app/models/detail_order.rb
class DetailOrder < ApplicationRecord
end

plataforma/app/models/invoice.rb
class Invoice < ApplicationRecord
end

plataforma/app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

plataforma/app/models/kind.rb
class Kind < ApplicationRecord
  has_many :pqrs
end

plataforma/app/models/order.rb
class Order < ApplicationRecord
end

plataforma/app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :kind
end

plataforma/app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :photos, PhotosUploader
  serialize :photos, JSON
  belongs_to :supplier
end

plataforma/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

plataforma/app/models/sale.rb
class Sale < ApplicationRecord
end

plataforma/app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
end

plataforma/app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :category
  has_many :products
end

plataforma/app/models/user.rb
 class User < ApplicationRecord

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

plataforma/app/helpers/categoria_helper.rb
module CategoriaHelper
end

plataforma/app/helpers/home_helper.rb
module HomeHelper
end

plataforma/app/helpers/pqrs_helper.rb
module PqrsHelper
end

plataforma/app/helpers/products_helper.rb
module ProductsHelper
end

plataforma/app/helpers/sale_helper.rb
module SaleHelper
end

plataforma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plataforma</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>


    <span class="nav-bar" id="btnMenu"><i class="fas fa-bars"> Menu</i></span>
    <nav class="main-nav">
      <ul class="menu" id="menu">
        <li class="menu__item"><a  class="menu__link" <%= link_to "Variedades Mary", root_path%></a></li>
        <li class="menu__item container-submenu">
          <a href="#" class="menu__link submenu-btn">Productos</a>
          <ul class="submenu">
            <li class="menu__item">
              <a class="menu__link" <%= link_to "Crear Producto", new_product_path%></a>
            </li>
            <li class="menu__item">
              <a class="menu__link" <%= link_to "Mostrar Producto", products_path%></a>
            </li>
          </ul>
        </li>
        <li class="menu__item container-submenu">

          <a href="#" class="menu__link submenu-btn">Proveedores</a>

          <ul class="submenu">
            <li class="menu__item"><a class="menu__link" <%= link_to "Crear Proveedores", new_supplier_path%> </a></li>
            <li class="menu__item"><a class="menu__link" <%= link_to "Mostrar Proveedores", suppliers_path%></a></li>
          </ul>
        </li>

        <li class="menu__item container-submenu">
          <a href="#" class="menu__link submenu-btn">PQR</a>
          <ul class="submenu">
            <li class="menu__item"><a class="menu__link" <%= link_to "Crear PQR", new_pqr_path%> </a></li>
            <li class="menu__item"><a class="menu__link" <%= link_to "Mostrar PQR", pqrs_path%></a></li>
          </ul>
        </li>
        <li class="menu__item container-submenu">
          <a href="#" class="menu__link submenu-btn"><i class="fas fa-user"></i></a>
          <ul class="submenu">

            <% if  user_signed_in?%>
              <li class="menu__item"><a class="menu__link" <%= link_to "Editar Perfil", edit_user_registration_path%></a></li>
              <li class="menu__item"><a class="menu__link" <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></a></li>

              <% elsif %>
              <li class="menu__item"><a class="menu__link" <%= link_to "Iniciar Sesion", new_user_session_path%></a></li>
              <li class="menu__item"><a  class="menu__link" <%= link_to "Registrarme", new_user_registration_path %></a></li>

            <% end %>

          </ul>
        </li>
      </ul>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>



    <header>

    </header>
    <section>
      <%= yield %>
    </section>

    <footer>

      <%= javascript_pack_tag 'menu' %>




  </body>
</html>