plataforma/config/routes.rb
Rails.application.routes.draw do

  # get 'categoria/index'
  # get 'categoria/new'
  devise_for :users
  # get 'suppliers/index'
  # get 'suppliers/new'
  # get 'suppliers/show'
  # get 'suppliers/edit'
  # get 'products/index'
  # get 'products/new'
  # get 'products/show'
  # get 'products/edit'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :products
  resources :suppliers
  resources :pqrs
  resources :sale
  resources :categoria
end

plataforma/app/models/add_kind.rb
class AddKind < ApplicationRecord
end

plataforma/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

plataforma/app/models/categoria.rb
class Categoria < ApplicationRecord
end

plataforma/app/models/category.rb
class Category < ApplicationRecord
  has_many :suppliers
end

plataforma/app/models/detail_order.rb
class DetailOrder < ApplicationRecord
end

plataforma/app/models/invoice.rb
class Invoice < ApplicationRecord
end

plataforma/app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

plataforma/app/models/kind.rb
class Kind < ApplicationRecord
  has_many :pqrs
end

plataforma/app/models/order.rb
class Order < ApplicationRecord
end

plataforma/app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :kind
end

plataforma/app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :photos, PhotosUploader
  serialize :photos, JSON
  belongs_to :supplier
end

plataforma/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

plataforma/app/models/sale.rb
class Sale < ApplicationRecord
end

plataforma/app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
end

plataforma/app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :category
  has_many :products
end

plataforma/app/models/user.rb
 class User < ApplicationRecord

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

plataforma/app/controllers/suppliers_controller.rb
# Esta clase Suppliers funcionara como controlador para renderizar hacia la vista Pqrs con sus rescpectivos metodos
# @Autor: David Cabrera - Desarrollador
# @version: 1.0
# @see <a href="http://www.variedadesmary.com">Variedades Mary</a>

class SuppliersController < ApplicationController

  before_action :authenticate_user!

  # @param: Metodo index que traera todos los registros de la tabla suppliers de nuestra base de datos
  def index
    if current_user.has_role? :admin
    @suppliers = Supplier.all
    else
    flash[:alert] = "No tiene acceso"
    redirect_to root_path
    end
  end

  # @param: Metodo new que permitira crear nuevo registro en la tabla suppliers
  def new
    @supplier = Supplier.new
  end

  # @param: Metodo show que traera un registro en especifico de la tabla suppliers
  def show
    @supplier = Supplier.find(params[:id])
  end

 # @param: Metodo create donde se creara el registro en la tabla suppliers
  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to suppliers_path
    else
      render :new
    end
  end

  # @param: Metodo edit que permitira editar un registro en la tabla suppliers
  def edit
    @supplier = Supplier.find(params[:id])
  end

  # @param: Metodo update que permitira actualizar nuevo registro en la tabla suppliers
  def update
    @supplier = Supplier.find(params[:id])
      if @supplier.update(supplier_params)
        redirect_to suppliers_path
      else
        render :edit
      end
  end

  # @param: Metodo destroy que permitira eliminar un registro en la tabla suppliers
  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy
    redirect_to suppliers_path
  end


  private

  def supplier_params
    params.require(:supplier).permit(:code_suppliers, :id_person, :nit_company, :fullname, :kind, :sex, :email, :telephone, :address, :photo, :category_id)
  end

end

plataforma/app/helpers/categoria_helper.rb
module CategoriaHelper
end

plataforma/app/helpers/home_helper.rb
module HomeHelper
end

plataforma/app/helpers/pqrs_helper.rb
module PqrsHelper
end

plataforma/app/helpers/products_helper.rb
module ProductsHelper
end

plataforma/app/helpers/sale_helper.rb
module SaleHelper
end

plataforma/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

plataforma/app/views/suppliers/edit.html.erb
<h1>Actualizar Proveedor</h1>


<div class="form_suppliers">
  <%= simple_form_for @supplier do |f| %>
  <%= f.association :category, label_method: :kind%>
    <%= f.input :fullname, label: "Nombre Completo" %>
    <%= f.input :sex, label: "Sexo" %>
    <%= f.input :email, label: "Correo electronico" %>
    <%= f.input :telephone, label: "Telefono" %>
    <%= f.input :address, label: "Direccion"%><br>
    <div class="d-grid gap-2">
      <%= f.button :submit, "Actualizar Proveedor", :class => "btn btn-primary"%>
    </div>

  <% end %>
</div>

plataforma/app/views/suppliers/index.html.erb
<h1>Proveedores</h1>

<table class="table table-striped table-hover">
  <tr>
    <thead class="">
      <th scope="col">Tipo</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">Sexo</th>
      <th scope="col">Correo electronico</th>
      <th scope="col">Telefono</th>
      <th scope="col">Direccion</th>
      <th scope="col">Accion</th>
    </thead>
  </tr>

<% @suppliers.each do |supplier| %>
<tr>
  <td><%= supplier.category_id %></td>
  <td><%= supplier.fullname %></td>
  <td><%= supplier.sex %></td>
  <td><%= supplier.email %></td>
  <td><%= supplier.telephone %></td>
  <td><%= supplier.address %></td>
  <td>
    <%= link_to "Editar", edit_supplier_path(supplier), :class => "btn btn-primary"%>
    <%= link_to "Eliminar", supplier, method: :delete, data: {confirm: "Desea eliminar este proveedor?"}, :class => "btn btn-danger" %>
  </td>

</tr>
<% end %>
</table>

plataforma/app/views/suppliers/new.html.erb
<div class="form_suppliers">
  <h1>Nuevo Proveedor</h1>
  <%= simple_form_for @supplier do |f| %>
    <%= f.association :category, label_method: :kind%>
    <%= f.input :fullname, label: "Nombre Completo" %>
    <%= f.label :'Sexo:' %><br>
    <%= f.select(:sex, ['Masculino', 'Femenino', 'Otro'])%>
    <%= f.input :email, label: "Correo electronico" %>
    <%= f.input :telephone, label: "Telefono" %>
    <%= f.input :address, label: "Direccion"%> <br>
    <div class="d-grid gap-2">
      <%= f.button :submit, "Crear Proveedor", :class => "btn btn-primary"%>
    </div>

  <% end %>
</div>

plataforma/app/views/suppliers/show.html.erb
<h1>Suppliers#show</h1>
<p>Find me in app/views/suppliers/show.html.erb</p>