plataforma/config/routes.rb
Rails.application.routes.draw do

  # get 'categoria/index'
  # get 'categoria/new'
  devise_for :users
  # get 'suppliers/index'
  # get 'suppliers/new'
  # get 'suppliers/show'
  # get 'suppliers/edit'
  # get 'products/index'
  # get 'products/new'
  # get 'products/show'
  # get 'products/edit'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :products
  resources :suppliers
  resources :pqrs
  resources :sale
  resources :categoria
end

plataforma/app/models/add_kind.rb
class AddKind < ApplicationRecord
end

plataforma/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

plataforma/app/models/categoria.rb
class Categoria < ApplicationRecord
end

plataforma/app/models/category.rb
class Category < ApplicationRecord
  has_many :suppliers
end

plataforma/app/models/detail_order.rb
class DetailOrder < ApplicationRecord
end

plataforma/app/models/invoice.rb
class Invoice < ApplicationRecord
end

plataforma/app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

plataforma/app/models/kind.rb
class Kind < ApplicationRecord
  has_many :pqrs
end

plataforma/app/models/order.rb
class Order < ApplicationRecord
end

plataforma/app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :kind
end

plataforma/app/models/product.rb
class Product < ApplicationRecord
  mount_uploaders :photos, PhotosUploader
  serialize :photos, JSON
  belongs_to :supplier
end

plataforma/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

plataforma/app/models/sale.rb
class Sale < ApplicationRecord
end

plataforma/app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
end

plataforma/app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :category
  has_many :products
end

plataforma/app/models/user.rb
 class User < ApplicationRecord

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

plataforma/app/controllers/pqrs_controller.rb
# Esta clase Pqrs funcionara como controlador para renderizar hacia la vista Pqrs con sus rescpectivos metodos
# @Autor: David Cabrera - Desarrollador
# @version: 1.0
# @see <a href="http://www.variedadesmary.com">Variedades Mary</a>

class PqrsController < ApplicationController

  # @param: Metodo index que traera todos los registros de la tabla pqrs de nuestra base de datos
  def index
    @pqrs = Pqr.all
  end

  # @param: Metodo new que permitira crear nuevo registro en la tabla pqrs
  def new
    @pqr = Pqr.new
  end

  # @param: Metodo show que traera un registro en especifico de la tabla pqrs
  def show
  end

  # @param: Metodo create donde se creara el registro en la tabla pqrs
  def create
    @pqr = Pqr.new(pqr_params)
    if @pqr.save
      redirect_to pqrs_path
    else
      render :new
    end
  end
  # @param: Metodo edit que permitira editar un registro en la tabla pqrs
  def edit
    @pqr = Pqr.find(params[:id])
  end

    # @param: Metodo update que permitira actualizar nuevo registro en la tabla pqrs
  def update
    @pqr = Pqr.find(params[:id])
      if @pqr.update(pqr_params)
        redirect_to pqrs_path
      else
        render :edit
      end
  end

    # @param: Metodo destroy que permitira eliminar un registro en la tabla pqrs
  def destroy
    @pqr = Pqr.find(params[:id])
    @pqr.destroy
    redirect_to pqrs_path
  end


  private

  def pqr_params
    params.require(:pqr).permit(:code_pqr, :code_customer, :code_sale, :kind, :description, :state, :reference, :date, :kind_id)
  end

end

plataforma/app/helpers/categoria_helper.rb
module CategoriaHelper
end

plataforma/app/helpers/home_helper.rb
module HomeHelper
end

plataforma/app/helpers/pqrs_helper.rb
module PqrsHelper
end

plataforma/app/helpers/products_helper.rb
module ProductsHelper
end

plataforma/app/helpers/sale_helper.rb
module SaleHelper
end

plataforma/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

plataforma/app/views/pqrs/edit.html.erb
<h1>Pqrs#edit</h1>
<p>Find me in app/views/pqrs/edit.html.erb</p>

plataforma/app/views/pqrs/index.html.erb
<h1>PQR</h1>
<hr>
 <table class="table table-striped table-hover">
   <tr>
     <thead class="">
       <th scope="col">Tipo</th>
       <th scope="col">Descripcion</th>
       <th scope="col">Estado</th>
       <th scope="col">Referencia</th>
       <th scope="col">Fecha</th>
       <th scope="col">Accion</th>

     </thead>
   </tr>
   <% @pqrs.each do |pqr| %>
   <tr>
     <td><%= pqr.kind_id %></td>
     <td><%= pqr.description %></td>
     <td><%= pqr.state %></td>
     <td><%= pqr.reference %></td>
     <td><%= pqr.date %></td>
     <td>
       <%= link_to "Editar", edit_pqr_path(pqr), :class => "btn btn-primary"%>
       <%= link_to "Eliminar", pqr, method: :delete, data: {confirm: "Desea eliminar este proveedor?"}, :class => "btn btn-danger" %>
     </td>
   </tr>
   <% end %>
 </table>

plataforma/app/views/pqrs/new.html.erb
<h1>Nuevo PQR</h1>


<div class="form_suppliers">
  <%= simple_form_for @pqr do |f| %>
    <%= f.association :kind, label_method: :kind%>
    <%= f.input :description, label: "Descripcion" %>
    <%= f.input :state, label: "Estado" %>
    <%= f.input :reference, label: "Referencia" %>
    <%= f.input :date, label: "Fecha" %><br>
    <div class="d-grid gap-2">
      <%= f.button :submit, "Crear PQR", :class => "btn btn-primary"%>
    </div>

  <% end %>
</div>

plataforma/app/views/pqrs/show.html.erb
<h1>Pqrs#show</h1>
<p>Find me in app/views/pqrs/show.html.erb</p>